### ISSUE TITLE
Raise warning on download when GEO accession doesn't have matching SRA data

### ISSUE THREAD

**Issue by mbelmadani** [PavlidisLab/rnaseq-pipeline#3] opened 2018-07-09 22:03 UTC
Experiments from GEO can sometimes have an accession but not actually have SRA data. An example is `GSE64018`. 

Currently the pipeline will not see this as a failure on `DownloadGSE`, but the Qc step will fail (assuming the `--nsamples` argument from `QcGSE` is not 0). It would be nicer if DownloadGSE would either return a failure when it can't find a matching SRA accession from the MINIML file, or at least raise a loud warning so the problem is obvious to the pipeline user.

**Comment by arteymix** [comment] 2019-10-17 18:35
The issue is resolved in 2b45360e6c17f6b42dea170724f44d05a26ea208 as we now check that one and only one SRR is retrieved per GSM.

**Closed by arteymix** 2019-10-17 18:35 UTC
Labels: enhancement, good first issue
